OBJ = bitmap.o interp.o realft.o Mat_DP.o

fig2-3: fig2-3.o CT.o $(OBJ)
	g++ fig2-3.o CT.o $(OBJ)
fig4-5: fig4-5.o FastCT.o $(OBJ)
	g++ fig4-5.o FastCT.o $(OBJ)
fig7: fig7.o FastCT.o $(OBJ)
	g++ fig7.o FastCT.o $(OBJ)
